name: Build and Deploy to Netlify
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "package.json"
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: yarn install
    - name: Publish
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_CMD: yarn build
        NETLIFY_DIR: build
